version: "3.9"

services:
  react:
    build: ./front
    container_name: front_react
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/front/src:/usr/src/app/src
    command: npm run start

  rails:
    build: ./back
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ${PWD}/backRakuten:/usr/src/app/var/www/back
    ports:
      - 3000:3000
    depends_on:
      - mysql
    tty: true
    stdin_open: true
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume:
