version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/backRakuten
    steps:
      - checkout:
          path: ~/backRakuten
      - ruby/install-deps
  test:
    docker:
      - image: circleci/ruby:2.6.5
      - image: circleci/mysql:5.7.25
        environment:
          MYSQL_DATABASE: backRakuten_test
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: 127.0.0.1
      RAILS_ENV: test
    working_directory: ~/backRakuten
    steps:
      - checkout:
          path: ~/backRakuten
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: User Model test
          command: bundle exec rspec spec/models/user_spec.rb
      - run:
          name: Book Model test
          command: bundle exec rspec spec/models/book_spec.rb
      - run:
          name: API Requests test
          command: bundle exec rspec spec/requests/api/v1/books_spec.rb
workflows:
  version: 2
  build_test_deploy_to_fargate:
    jobs:
      - build
      - test:
          requires:
            - build
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          repo: memento_rails
          tag: latest
          path: ./
          dockerfile: Dockerfile
          requires:
            - test
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          aws-region: AWS_DEFAULT_REGION
          cluster-name: teddytime
          family: teddytime_api
          service-name: teddytime_api
          container-image-name-updates: "container=memento_rails_only,image-and-tag=${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}/memento_rails:latest"
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: master
